name: Push Docker Image

on:
  push:

jobs:
  push_to_registry:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major_tag: [ "6.2.8", "6.2.9", "6.2.10", "6.2.11", "6.2.12", "6.2.13", "7.0.0", "7.0.1", "7.0.2", "7.0.3", "7.0.4", "7.0.5", "7.0.6", "7.0.7", "7.0.8", "7.0.9", "7.0.10", "7.0.11", "7.0.12", "7.0.13", "7.0.14", "7.2.0", "7.2.1", "7.2.2", "7.2.3" ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          major_tag=${{ matrix.major_tag }}
          
          echo "Processing version: $major_tag"

          docker build --build-arg redis_version=$major_tag -t current_build .
          docker tag current_build himadieievsv/redis-cluster:$major_tag

          docker push himadieievsv/redis-cluster:$major_tag
