name: Push Latest Docker Image

on:
  schedule:
    - cron:  '0 14 * * *'

jobs:
  push_to_registry:
    name: Build and Push Latest Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          
          response=$(curl -s "https://api.github.com/repos/redis/redis/releases/latest" )
          
          major_tag=$(echo "$response" | jq .name -r)
          target_commitish=$(echo "$response" | jq .target_commitish -r)
          
          
          docker pull "himadieievsv/redis-cluster:$major_tag" > /dev/null 2>&1 || { 
             echo "Tag exists in the registry"
             continue_var=true
          }

          # Check the exit code of the pull command
          if [ ! -v continue_var ]; then
             echo "Tag $major_tag exists for himadieievsv/redis-cluster"
             echo "Exiting the script"
             exit 0
          fi

          docker build --build-arg redis_version=$major_tag -t current_build .
          docker tag current_build himadieievsv/redis-cluster:$major_tag
          docker tag current_build himadieievsv/redis-cluster:$target_commitish
          docker tag current_build himadieievsv/redis-cluster:latest

          docker push himadieievsv/redis-cluster:$major_tag
          docker push himadieievsv/redis-cluster:$target_commitish
          docker push himadieievsv/redis-cluster:latest
