name: Push Docker Images for Major tags

on:
  schedule:
    - cron:  '15 * * * *'

jobs:
  push_to_registry:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major_tag: [ "6.0", "6.2", "7.0", "7.2", "7.4" ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          major_tag=${{ matrix.major_tag }}
          

          # Make the API request to list tags
          response=$(curl -s "https://api.github.com/repos/redis/redis/git/refs/tags")
          # Parse the JSON response to extract tags

          latest_tag=$(echo "$response" | jq -r '.[].ref' | grep "^refs/tags/$major_tag\." | tail -n 1)
          extracted_version=$(echo "$latest_tag" | sed 's/refs\/tags\///')

          docker build --build-arg redis_version=$extracted_version -t current_build .
          docker tag current_build himadieievsv/redis-cluster:$extracted_version
          docker tag current_build himadieievsv/redis-cluster:$major_tag

          docker push himadieievsv/redis-cluster:$extracted_version
          docker push himadieievsv/redis-cluster:$major_tag
